### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by preraksola** [Steinblock/redmine-gitlab-migrator#4]
Hello,

I am having some weird issue now. For one of my migrations, I migrated the Roadmap first and after that I executed the command to migrate the issues.
The first issue was migrated successfully, but for the second one I got the below error:

Command:
```
migrate-rg issues --redmine-key xxx --gitlab-key yyy https://redmine.xx.net/projects/x https://gitlab.xx.com/group1/x
```

Output:
```
INFO: Project has no pre-existing issue...
INFO: Project has no pre-existing issue... OK
INFO: Getting redmine issues
INFO: Converting issues
INFO: Creating gitlab issues
WARNING: Redmine issue #655 is anonymous, gitlab issue is attributed to current admin

WARNING: Redmine user {'id': 7, 'name': 'foo'} is unknown, attribute note to current admin

WARNING: Redmine issue #655 assignee is anonymous. gitlab assinee is attributed to current admin

INFO: #5 -RM-655-MR-Authentification ADFS/AD
WARNING: Redmine issue #638 assignee is anonymous. gitlab assinee is attributed to current admin

INFO: create issue "-RM-638-MR-[x] Ajouter la possibilité de sélectionner les colonnes à afficher" failed
Traceback (most recent call last):
  File "/usr/local/bin/migrate-rg", line 11, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.3', 'console_scripts', 'migrate-rg')()
  File "/usr/local/lib/python3.5/dist-packages/redmine_gitlab_migrator-1.0.3-py3.5.egg/redmine_gitlab_migrator/commands.py", line 308, in main
  File "/usr/local/lib/python3.5/dist-packages/redmine_gitlab_migrator-1.0.3-py3.5.egg/redmine_gitlab_migrator/commands.py", line 191, in perform_migrate_issues
  File "/usr/local/lib/python3.5/dist-packages/redmine_gitlab_migrator-1.0.3-py3.5.egg/redmine_gitlab_migrator/gitlab.py", line 141, in create_issue
  File "/usr/local/lib/python3.5/dist-packages/redmine_gitlab_migrator-1.0.3-py3.5.egg/redmine_gitlab_migrator/__init__.py", line 47, in post
  File "/usr/local/lib/python3.5/dist-packages/redmine_gitlab_migrator-1.0.3-py3.5.egg/redmine_gitlab_migrator/__init__.py", line 38, in _req
  File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://gitlab.xx.com/api/v3/projects/32/issues
```

It's quite weird because, the gitlab API can access the project for first issue and not for the second one.

Is there anything that could be done to resolve this?

Thanks,
Prerak

**Comment by Steinblock** [comment]
From #3 
> Also, I turned off the user ceck by commenting the line (check_users, 'Required users presence'), from commands.py.

Maybe the user or assignee is missing? Try to enable it again.

Otherwise I would suggest you look in the gitlab logs for an error message or stacktrace but you have to be an admin. `https://gitlab.xx.com/admin/logs` -> production.log 

Or via shell `sudo gitlab-ctl tail | grep projects/32/issues`

**Comment by preraksola** [comment]
I don't think it's because of the user. The issue that migrates successfully is assigned to the same user.
Also, in the logs, I cannot see any error or stacktrace. There's just lines about incoming requests and nothing else.

**Comment by Steinblock** [comment]
In Redmine you have the `author` (who created the ticket) the `assigned_to` and for every comment (notes), a user too. 

I know I had the same problem as you and solved it somehow by double checking every redmine user is present in gitlab (I can't remember but maybe I had to reenable deleted users in redmine).
I improved logging in `check_users` so you can compare redmine and gitlab users.
```
log.info('Redmine users are: {}'.format(', '.join(redmine_user_names) + ' '))
log.info('GitLab users are: {}'.format(', '.join(gitlab_user_names) + ' '))
```

Please investigate the output to be sure. And maybe you can look at the redmine issue xml 

https://redmine.company.tld/issues/1234.xml?include=attachments,children,relations,changesets,journals,watchers

and look if there is somebody who is unknown to gitlab.

**Comment by preraksola** [comment]
I got it working by changing the `Visibility Level` of the project from "Private" to "Internal".
However, for one of the other project, I was able to migrate the issues successfully even though the Visibility Level was Private.

The only difference between these two projects is the one that succeeded with Private status is under a group and the one that succeeded with Internal level is under a user's account.

Any idea regarding why his could be happening?

**Comment by Steinblock** [comment]
Interesting,

while migrating projects I always added users explicitly to the project and later removed them because they where part of the group.

Maybe one user was already known inside gitlab but had no permission for this private project.
After changing it to internally issue creation succeded.

(Tipp: If you enable --debug you can output the raw data which would be passed to gitlab).

**Comment by preraksola** [comment]
Yeah, that might be the case. I had a user on Gitlab same as redmine, but was not added under the project on which I was performing the migrations.

Thanks for the info :+1:

**Comment by denisvm** [comment]
@preraksola I've ran into the same issue. The changesets associated to the issue in Redmine contained an user that wasn't registered in both Redmine and GitLab. In my case it was a small issue related to SVN to Git migration that I've fixed manually. After fixing it and reloading the changesets in Redmine everything ran smoothly.
